### ISSUE TITLE
HTTP 500 triggers delegate method for Finished and not Failed?

### ISSUE THREAD

**Issue by jasconius** [pokeb/asi-http-request#139]
Any particular reason why? Under what circumstances is HTTP 500 not a request failure?

Occurring on v1.8-33

**Comment by leepa** [comment]
The request hasn't failed - the server has. Technically the request itself isn't a failure but the server is. The request completed successfully - you connected and got a response.

**Comment by pokeb** [comment]
IIRC HTTP authentication failure is the only status code that ASIHTTPRequest directly handles as an error (CFNetwork may handle others and pass them on as a stream error to ASIHTTPRequest, but I'm not sure).

I guess the problem is there are so many status codes, and so many ways of interpreting them. Any status code you weren't expecting is potentially an error, but this will vary from app to app - I think trying to handle these in ASIHTTPRequest would be a mistake.
