### ISSUE TITLE
S3 upload file missing data on device, but not on simulator

### ISSUE THREAD

**Issue by rpstro02** [pokeb/asi-http-request#14]
I'm experiencing an issue with an Amazon S3 file upload.  The simulator works great.  But the exact same code on the device doesn't seem to upload the entire 166 Kb .png picture file.  It only seems to upload 159 Kb.  When I try to open the image, I get an error.  I've tried both 3G network and WiFi.  Both with the same result.  Anyone experienced this issue or know what the problem could be?  I am on an iPhone 3Gs running OS 3.1.

**Comment by rpstro02** [comment]
Update.  The issue seems to only be with PNG files.  I think it might be similar to the same problem that occurs on the cocoahttpserver here:

http://code.google.com/p/cocoahttpserver/issues/detail?id=15#c4

I'm not sure what the deal is with png files on the iPhone.

**Comment by rpstro02** [comment]
I think I could fix the issue the same way the cocoahttpserver fixes the issue if I stream a file from memory as opposed to from the disk.  I'm not sure how to do that right now. If anyone does, please post.

**Comment by pokeb** [comment]
Are you trying to upload a png you added to your project?

If I'm reading it correctly, the problem on the link you sent seems to be related to Xcode pre-multiplying the alpha on the image, which makes the png unreadable by other apps.

To use the fix they suggest, try something like this:

UIImage *imagePNG= [UIImage imageWithContentsOfFile:filePath];
NSData *pngData= UIImagePNGRepresentation(imagePNG);
[pngData writeToFile:somewhere atomically:NO];
ASIS3Request *request = [ASIS3Request PUTRequestForFile:somewhere withBucket:bucket path:path];

Writing it back to a file is necessary because ASIS3Request doesn't have support for uploading data except from a file, though I think this would be a worthwhile addition to the class.

Thanks

Ben

**Comment by rpstro02** [comment]
Thanks for the reply.  I'm trying to upload a png that I added to the project bundle.  I tried to read the file straight from disk.  I will try what you're suggesting.  I am pretty sure there is some sort of issue with the alpha on the image because when I view image info of the uploaded file, it's different from the alpha value of the original image.

Uploading from data would rock!

**Comment by pokeb** [comment]
Added PUTRequestForData:etc to ASIS3Request
Closed by b3de943af8c6f37192990c413666c85217146d07.

Also fixed unit tests for S3 on Mac, continued fallout from that setDoubleValue: debacle
