### ISSUE TITLE
setUsername and setPassword acts strangely (new version)

### ISSUE THREAD

**Issue by kukosk** [pokeb/asi-http-request#150]
Hi,

I've found a bug. Maybe it's because im running in the simulator (don't know how it goes on device), but when i try to subclass ASIPostDataRequest, and [self setUsername...] or [self setPassword...] in a method in the class I created, it acts really strange. when i run the app, the first request sends no username and password at all ... the second is okay ... but when i try to change the username, or pass while running the app, it doesn't change at all ... and it should ... I was trying to solve this one for over an hour or so, and then i used an older version of asihttp, and it worked ...

**Comment by pokeb** [comment]
Hi Jakub

There was a recent change in the behaviour of basic authentication. If you want to send basic authentication credentials on your very first request, you need to do this:

[request setAuthenticationScheme:(NSString *)kCFHTTPAuthenticationSchemeBasic];

If you don't do this, ASIHTTPRequest will automatically retry your request with the credentials after it has failed authentication. It should still work as before, but it's less efficient (especially if you're sending data in the request body) because you have to hit the server twice.

I hadn't quite realised that this change would have broken changing the username and password. Looking at the code it looks like this used to work for basic auth, but not digest or NTLM. I have made some changes in this branch:

https://github.com/pokeb/asi-http-request/tree/auth-tweaks

Which should fix this, but it's quite a big change so I'd like to see if others find issues before merging it.

Many thanks

Ben

**Comment by kukosk** [comment]
Thank you pokeb :)

**Comment by pokeb** [comment]
This is merged into master now, so I'll close this one.
