### ISSUE TITLE
Cannot initialize ASIHTTPRequest via init

### ISSUE THREAD

**Issue by leafduo** [pokeb/asi-http-request#156]
Why I cannot do ASIHTTPRequest *r = [[ASIHTTPRequest alloc] init], but ASIHTTPRequest *r = [[ASIHTTPRequest alloc] initWithURL:nil] ?

**Comment by pokeb** [comment]
I don't think there's any reason why you can't use init instead, but you'd need to set the url on a separate line, and initWithURL sets up sensible defaults for many standard request properties for you. I don't think there would be any use for a request that doesn't have a url set, since you need a url to do pretty much anything. Anyway, [ASIHTTPRequest requestWithURL:url] is the simplest way to create a request.
