### ISSUE TITLE
[ASIHTTPRequest defaultUserAgentString] - takes a long time...

### ISSUE THREAD

**Issue by LeeMatthewHiggins** [pokeb/asi-http-request#159]
[ASIHTTPRequest defaultUserAgentString] takes a long time due to system calls, it regenerates the string each time. Could we cache it instead?
We've shaved off 5 seconds from our multi request monster download by doing this.

**Comment by steipete** [comment]
I also noted this Issue. As a workaround, just create a UserAgentString yourself and set it on every request (or hack the framework; it's both pretty easy)

**Comment by pokeb** [comment]
There's been a pull request to have ASIHTTPRequest generate the default user agent once and let the user set it themselves open since...forever. I promise this _really_ is at the top of the list to merge as soon as I get a bit of time...my humblest apologies for taking so long to get this sorted! :)

**Comment by steipete** [comment]
I figured that you must be really busy, asi was updated so frequently, but lately it's been a bit quiet about the project... ;)

**Comment by pokeb** [comment]
I've merged a tweaked version of Garrett's original pull request now, so I'll close this one.
