### ISSUE TITLE
ASIWebPageRequest - Caching of external data

### ISSUE THREAD

**Issue by kbgo** [pokeb/asi-http-request#170]
There is a inconsistency between SessionStore and PermanentStore when it comes to images, and most likely all external data.

I'm starting a ASIWebPageRequest with

[request setCachePolicy: ASIAskServerIfModifiedCachePolicy | ASIFallbackToCacheIfLoadFailsCachePolicy ];
[request setCacheStoragePolicy:ASICachePermanentlyCacheStoragePolicy];
[request setUrlReplacementMode: ASIReplaceExternalResourcesWithData];

The idea behind this is that the app uses the cached version, if it has any.
In webPageFetchSucceeded: I parse the request to get the reponse:

NSString *response = [NSString stringWithContentsOfFile:
                          [theRequest downloadDestinationPath] encoding:[theRequest responseEncoding] error:nil];

Now to the issue: If the request can contact the server, it loads the data into the /ASIHTTPRequestCache/SessionStore/, replaces the image with the data, and everything loads just fine.

However, if the request has to fallback to the permanent store, it loads the data from /ASIHTTPRequestCache/PermanentStore/, in which the image links are still the original links, and neither the data like in the session store nor local URLs pointing to the cached version.

Secondary Issue:
If I set the URLReplacementMode to ASIReplaceExternalResourcesWithLocalURLs, images are not displayed at all, though they are correctly downloaded to the permanent store, because the links are still pointing to the original path (you get the same file like in the above case if you have a fallback).

Any feedback is appreciated

Klaus

**Comment by kbgo** [comment]
Ok, I found a workaround at least: 

Set the Download destination path _after_ configuring the request! This works for ASIReplaceExternalResourcesWithData.
Still no success with ASIReplaceExternalResourcesWithLocalURLs though.

**Comment by pokeb** [comment]
If you don't set a downloadDestinationPath manually, responses will be cached unparsed (ie without links replaced). If data is pulled from the cache, ASIWebPageRequest won't re-parse the response. I'm guessing this is the cause of the problem you are seeing.

As noted in the example code, the best approach is to ask the cache for a downloadDestinationPath:

```
[request setDownloadDestinationPath:
  [[ASIDownloadCache sharedCache] pathToStoreCachedResponseDataForRequest:request]]];
```

I've just done a quick test using this approach, and was able to get ASIWebPageRequests using either replacement mode to cache permanently, and to display correctly in a web view when internet connectivity is turned off.

A couple of side nodes:
- Take care to clear cached data before switching between replacement modes - a mix of cached data from both modes can cause odd behaviour.
- ASIAskServerIfModifiedWhenStaleCachePolicy is probably better than ASIAskServerIfModifiedCachePolicy for almost all ASIWebPageRequests because of the overhead of conditional GETs for all the external resources.

Best

Ben

**Comment by kbgo** [comment]
Thanks Ben, I'm going to try that!
