### ISSUE TITLE
startSynchronous in background thread fails to connect to auth'd site

### ISSUE THREAD

**Issue by csdillard** [pokeb/asi-http-request#178]
If you startSynchronous in a background thread, the authentication dialog will appear (on the main thread).  But in the meantime, the [request startSynchronous] has (almost) immediately returned and the status is 401.  I would have expected startSynchronous to block until the user either enters a correct password or they cancel the dialog.

This can be duplicated readily with the iPad sample in the following way:  (1) Add an NSOperationQueue\* myQueue ivar to AuthenticationViewController. (2) Tweak the top of its @implementation to look like this:

@implementation AuthenticationViewController

-(void) doSomething {
    [self setRequest:[ASIHTTPRequest requestWithURL:[NSURL URLWithString:@"http://allseeing-i.com/top_secret/"]]];
    [request setUseKeychainPersistence:[useKeychain isOn]];
    [request setShouldPresentAuthenticationDialog:[useBuiltInDialog isOn]];
    [request startSynchronous];
    NSLog(@"Status: %d", [request responseStatusCode]);
}

-(IBAction) fetchTopSecretInformation:(id)sender
{
    if (myQueue == nil) {
        myQueue = [[NSOperationQueue alloc] init];
    }
    NSInvocationOperation\* op = [[NSInvocationOperation alloc] initWithTarget:self selector:@selector(doSomething) object:nil];
    [myQueue addOperation:op];
}

(3) Then run the authentication sample and observe the debug output.  Be sure to select the built-in dialog option.

**Comment by pokeb** [comment]
I fear this is partly a problem with the documentation - I don't think ASIHTTPRequest currently supports the use of ASIAuthenticationDialog in synchronous requests on _any_ thread (not only on the main thread, as the docs suggest).

It might be possible to get this working for synchronous requests on a secondary thread by using a lock, but I wonder how many people would find this useful.

I don't want to force people into using ASIHTTPRequest's standard model for async operations, but if you're running requests synchronously on a background thread, it suggests to me that the requests really ought to be able to run without user intervention. With this pattern, there's even less guarantee that presenting a dialog won't be interrupting something else, since you've effectively decoupled your networking flow from your UI entirely.

ASIHTTPRequest does have a somewhat opinionated threading model (asynchronous requests on a single background thread, with callbacks on the main thread) that does make it more difficult to use when you want something different - you're more or less forced into using synchronous requests. That said, if you feel strongly that this ought to be properly supported, let me know, and I'd be happy to look at this again.

Best,

Ben

**Comment by csdillard** [comment]
Ah, okay.  Thanks for the comment.  I agree that minor tweaks to the documentation might be worthwhile.  My choice to do synchronous downloads in a background thread was mostly laziness for a quick-and-dirty demo.

And once I switched to asynch requests, everything worked as expected.  The code is a little messier (since local variables had to be made into class ivars, and the logic had to be spread over a few methods), but it's certainly more consistent with the "normal" way of doing business in ASIHTTPRequest and/or NSURLConnection.  And it's probably more resilient to failure as well.

Thanks!
