### ISSUE TITLE
Requests do not show accurate progress when added to queue

### ISSUE THREAD

**Issue by jpedroso** [pokeb/asi-http-request#232]
For example, an `ASIHTTPRequest` with `showAccurateProgress = YES` and a valid `uploadProgressDelegate` does not report progress to said delegate when added to a vanilla `ASINetworkQueue`, i.e. queue with `showAccurateProgress = NO` and nil progress delegates.

This comes from the fact that `ASINetworkQueue` always overrides request's `showAccurateProgress` on `-addOperation:`.  Sure one can pre-configure the queue with `showAccurateProgress = YES` too but wouldn't it be more reasonable to to only override `ASIHTTPRequest`'s `showAccurateProgress` when the queue has `showAccurateProgress = YES`? Any side-effects on this?

Can this be considered an improvement?

**Comment by pokeb** [comment]
ASINetworkQueue defaults to NO for showAccurateProgress, while ASIHTTPRequests defaults to YES, basically because accurate progress tracking is not normally what you want on a queue with many small requests. So, only overriding when the queue has accurate progress tracking turned on won't make any difference unless you've manually set the requests not to use accurate progress tracking.

I can see it might make sense to be able to accurately track progress for individual requests, but just use basic progress tracking to record overall progress on the queue. Does this sound like it would solve your problem?

**Comment by jpedroso** [comment]
No. In my specific scenario I only want to track progress on certain type of requests added to the queue, and don't want other request interfering reporting progress. I have query requests and upload request—only progress of upload requests matter.

Like I said, it's possible to workaround this by also setting `showAccurateProgress=YES` without delegates on the ASINetworkQueue. The problem is that it relies on the value set on delegates of-the queue and the requests to receive the accurate progress on the right place. I could also use a separe queue…

Anyway, provided there are no side-effects, this improvement suggestion comes in the light of the least astonishment principle for the programmer. Up to you to close the issue or let me know if you want a pull request from me. Thanks.

**Comment by pokeb** [comment]
Ok, using a separate queue is probably the best way to go if your progress tracking requirements for certain requests is different.

**Comment by jpedroso** [comment]
Ok. Closing the issue.

**Comment by edwardIshaq** [comment]
@jpedroso Thank you for this post. I was looking for a solution to why the progress is not showing when adding a request to the Queue.
