### ISSUE TITLE
Fix problems with ASIWebPageRequest and maxConcurrentOperationCount

### ISSUE THREAD

**Issue by pokeb** [pokeb/asi-http-request#253]
https://groups.google.com/forum/?hl=en-GB#!topic/asihttprequest/OdcIMHiBs7g

**Comment by RadhikaS** [comment]
There is a temporary fix for the problem that works for me. The problem is,upon request timeout ASIWebpageRequest never calls  super class(ASIHttpRequest) method markAsFinished which makes the timed out request to remain in the queue. 

I made the changes to ASIWebPageRequest.m

1.In markAsFinished method
- (void)markAsFinished
  {
  if (error) {
      [super markAsFinished];
  }  

}

Added the [super markAsFinished] call in case of an error. 
1. In externalResourceFetchFailed method
- (void)externalResourceFetchFailed:(ASIHTTPRequest *)externalResourceRequest
  {
  if([[self externalResourceQueue] shouldCancelAllRequestsOnFailure]){
      [self failWithError:[externalResourceRequest error]];
  }
  }

After making these changes i was able to download the webpage eventhough there are few timeouts and failures.
Note: Need to add the line  [[self externalResourceQueue] setShouldCancelAllRequestsOnFailure:NO];  to the methods parseAsHTML and parseAsCSS as mentioned in the bug.

**Comment by pokeb** [comment]
Thanks @RadhikaS - I have incorporated your fix! :)

**Comment by ghost** [comment]
Hi Ben,

I think there is unfortunately an issue with your implementation.

"should ignore errors"  is not  the same as   "should cancel"

[[self externalResourceQueue] setShouldCancelAllRequestsOnFailure:[self shouldIgnoreExternalResourceErrors]];

I think you are missing a " ! " in this line.

Thank you and
Best Regards,
Ralph
