### ISSUE TITLE
ASIAuthenticationDialog on iOS5

### ISSUE THREAD

**Issue by favormm** [pokeb/asi-http-request#277]
Today, I have update my xcode to 4.2 version.   I find  thd ASIAuthenticationDialog can't dismiss even if I click the cancle or login button.

Any one meet this problem?  And how to solve it?

**Comment by favormm** [comment]
I know the reason, that the iOS5 sdk parentViewController  return nil, should change to preventingViewController

**Comment by pthompson** [comment]
I didn't see an update in the code. Maybe it hasn't been merged yet?

To get it to work, I changed parentViewController to the presentingController property in the dismiss methods:
- (void)dismiss
  {
  [[sharedDialog presentingController] dismissModalViewControllerAnimated:YES];
  }
- (void)dismiss
  {
  if (self == sharedDialog) {
      [[self class] dismiss];
  } else {
  [[self presentingController] dismissModalViewControllerAnimated:YES];
  }
  }

**Comment by csdillard** [comment]
Just wanted to add another voice in hopes of getting this fixed in the next official version...

This issue seems to have been incorrectly closed.  It is still present in version 1.8.1.  And the fix mentioned above by pthompson and by gcox in #295 (using presentingViewController instead of parentViewController on iOS 5 and above) does indeed work.
