### ISSUE TITLE
queueDidFinishSelector selector called multiple times

### ISSUE THREAD

**Issue by andr8w** [pokeb/asi-http-request#29]
When shouldCancelAllRequestsOnFailure is set to YES, the queueDidFinishSelector gets called once per each failed/cancelled request. I was expecting it to be called only once per queue.

**Comment by pokeb** [comment]
Hi

I've just done a quick test and it seems to be working for me as expected - in a queue with 10 requests that all fail, the queueDidFinishSelector is only called once.

It would be great if you could post some code demonstrating the problem, and I'll take another look.

Best

Ben

**Comment by andr8w** [comment]
Hi Ben,

Thanks for looking into this.

It seems the issue is a combination of having shouldCancelAllRequestsOnFailure set to YES and setMaxConcurrentOperationCount set to 1.

I used your postWithProgress method in the Mac project sample to test. The sample code is at http://gist.github.com/335213 (modified postWithProgress method and added methods for the queue and request selectors).

When there's no network connection I get the following in the console:

postRequestStarted:; <ASIFormDataRequest: 0x195040>
postRequestFailed:; <ASIFormDataRequest: 0x195040>
postRequestFailed:; <ASIFormDataRequest: 0x2535b0>
postQueueDidFinish:; <ASINetworkQueue: 0x122450>
postQueueDidFinish:; <ASINetworkQueue: 0x122450>
postRequestStarted:; <ASIFormDataRequest: 0x2535b0>

Sometimes the last postRequestStarted is not logged.

Thanks,

Andrew

**Comment by pokeb** [comment]
Hi Andrew

Thanks very much for taking the time to track down the source of this problem! I've posted what I hope is a fix now, please let me know if you find problems.

To answer the question in your gist - yes, having separate delegate selectors in your queue and your requests is supported. The queue selectors were called first, but I've swapped the order now as well, so request delegate selectors should be called, then queue delegate selectors.

You still might get certain delegate methods called after your queueDidFinishSelector when requests fail - it's rather tricky to handle this problem, because of the way these selectors are called on the main thread 'at some point in the future'.

Thanks again!

Ben
