### ISSUE TITLE
ARC

### ISSUE THREAD

**Issue by tjrana** [pokeb/asi-http-request#316]
Please use ARC (Automatic Reference Counting).

**Comment by x2on** [comment]
+1

**Comment by ikarius** [comment]
Please don't :)
Wait until iOs reaches version 6, and that ARC can be really considered as mature...

**Comment by carlj** [comment]
+1 for "Please don't"

**Comment by andrewjl** [comment]
You can use -fno-objc-arc compiler flag in order to include non-ARC compatible libraries or classes.

More info here: http://stackoverflow.com/questions/6646052/how-can-i-disable-arc-for-a-single-file-in-a-project

On the other hand, +1 on "Please Don't" as well, not only is ARC immature but I'd rather see a library get additional functionality in lieu of ARC compatibility.

**Comment by x2on** [comment]
When you use a static library you don't need the compiler flag, only when you put the class files directly in your ARC project.

Why do you think ARC is immature? A lot of good apps use ARC.

**Comment by andrewjl** [comment]
Yes I stand corrected, static libraries it makes no difference.

I use ARC in all the iOS projects I'm working on but for 3rd party libraries all else equal I would rather see additional features put in rather than the library ported over to ARC. ARC also relies on the compiler to understand what you intend to happen memory wise and behaves erratically if you do not write idiomatic Cocoa code (in terms of method names, etc).

**Comment by ikarius** [comment]
Hi x2on,

I'm aware that there are many good apps that use ARC, but also that ARC does a pseudo static code replacement, that, in certain cases, can be erroneous.

However ARC seems to work fine in most cases, but that's not the relevant point for me.

The point is i don't want new iOs features (such as StoryBoards or ARC) in my production projects. 
I need to see how ARC behaves, and for at least 18 to 24 months.

ASI is just a fantastic lib, but it needs sustainability.
You just can't put ARC everywhere and expect the whole library to be stable anymore.

**Comment by Sam-Spencer** [comment]
Definitely +1 this. Although many developers here seem to like MRC, please note that ARC has now been around for quite a while. iOS 7 will be out soon, thats three releases of iOS with ARC (it also turns out that new Xcode 5 projects don't have an option to turn off ARC)! ARC also decreases the room for error and the need to manually manage memory. Plus, it makes it easier for others to make pull requests without needing to worry about memory management. ARC is definitely a standard now.

**Comment by ziggear** [comment]
+1 for "Please don't"
