### ISSUE TITLE
http 407 proxy authentication although Proxy setup contains credentials

### ISSUE THREAD

**Issue by MarceloEmmerich** [pokeb/asi-http-request#318]
My app does not currently work with proxies. Although the settings of the device's WiFi contain the proxy information, including credentials and no other app asks for proxy username/password, each request done with ASIHttpRequest ends up in a failure with a http 407. What could I be doing wrong?

Thanks,
Marcelo

**Comment by jogu** [comment]
That's expected behaviour and inherent in the design of ASIHTTPRequest / iOS.

ASIHTTPRequest builds up http requests itself rather than using the iOS NSURLConnection, so would need to manually add the proxy authentication headers. iOS does not allow the proxy username/password to be read queried by applications.

The only solutions are:

a. Use the built in dialogue to ask the user to provide the username/password

or:

b. Stop using ASIHTTPRequest and switch to NSURLConnection or one of the frameworks built on top of it (eg. AFNetworking)
