### ISSUE TITLE
ASIHTTPRequest works incorrectly with enable zombie objects.

### ISSUE THREAD

**Issue by Voloda2** [pokeb/asi-http-request#322]
ASIHTTPRequest caches my data when I use enable zombie objects. 

This topic explain a problem in full details.
http://stackoverflow.com/questions/10571969/asihttprequest-caches-my-data-i-dont-want-any-kind-of-cache/10572782#10572782

**Comment by jogu** [comment]
It doesn't seem to be caching the data, or at least nothing in that question says ASIHTTPRequest is caching it (by 'cacheing' I mean "holding the data in it's disc cache and using it without fetching it again if you make a request for the same url a second time".

This sounds like the expected behaviour of NSZombie, it's expected that enabling NSZombie for any application (even one not using ASIHTTPRequest) will increase the required memory.

**Comment by Voloda2** [comment]
Ok, it didn't caches. I agree with you.

I think ASIHTTPRequest has a problem when NSZombie in switch on state. It significantly increase the required memory.
For example, I have an app with 10 RAM. I even removed all code from request: didReceiveData:. My app will have 210 RAM if I download 200 MB file. 
Is it normal behavior?

**Comment by oscahie** [comment]
That's exactly the issue expected when running code with zombies enabled. The allocated objects won't actually release the memory on dealloc so that it is possible to keep track of messages sent to zombie objects rather than crashing.

@see http://cocoadev.com/wiki/NSZombieEnabled

**Comment by Voloda2** [comment]
You are right, thank you.
