### ISSUE TITLE
There are 5 warnings about input stream error not handled in SDK7.

### ISSUE THREAD

**Issue by V01dZer0** [pokeb/asi-http-request#370]
Hi @pokeb :
In SDK7 ,there are 5 warnings about input stream error not handled. Since a PR in my master branch hasn't be merged, I can't send another PR contains the commit https://github.com/OpenFibers/asi-http-request/commit/269f36c2c2a71c2ec7f798e211f250725e127c94 that fixed this issue.

If you can see this post, hope you can merge the two commits, I think they are really useful : D

Best regards

**Comment by jogu** [comment]
I don't think pokeb looks at anything anymore (see http://allseeing-i.com/%5Brequest_release%5D; )

I'd be happy to merge the warnings fix if you submit a pull request for that - I'm not sure about your other pull request about content-types; I believe that has a well known workaround originally suggested by pokeb (set the content type after calling buildrequest) so I'd be reluctant to go changing behaviour there (ie. I presume there's some reason Ben suggested a workaround rather than making code changes!).

**Comment by V01dZer0** [comment]
Sorry @jogu i reply you too late. The new github PR page is too hard to use for me, I don't know how to send PR to another fork of the original pokeb's repo, after a 30 minutes attempt.

Could you merge it by hand? Very sorry for it.

Best Regards : D

**Comment by jogu** [comment]
Okay, I've manually merged these, thanks, sorry for the delay. I also fixed an analyser warning in a different area.

Just to be clear, I've merged them into https://github.com/pokeb/asi-http-request/commits/master (ie. not my own fork - I have write access to pokeb's repository)
