### ISSUE TITLE
[ASIHTTPRequest handleNetworkEvent:]

### ISSUE THREAD

**Issue by rohitdhiman** [pokeb/asi-http-request#373]
Hi,
I am calling the webservice and using ASIHttprequest framework. I am getting crash occasionally  in 
ASIHTTPRequest.h/ASIHTTPRequest.m in -
- (void)handleNetworkEvent:(CFStreamEventType)type
  {

}

Could any 1 pls explore about this, why I am getting this crash? The description about this crash as on crittercism:
0. libobjc.A.dylib 0x3ac235d0 objc_msgSend + 16
1. MyProject 0x000e8f8b -[ASIHTTPRequest handleNetworkEvent:]
2. MyProject 0x000df13d ReadStreamClientCallBack
3. CoreFoundation 0x32d3ba6b _signalEventSync + 75
4. CoreFoundation 0x32d418b7 _cfstream_solo_signalEventSync + 75
5. CoreFoundation 0x32d3b7a3 _CFStreamSignalEvent + 327
6. CFNetwork 0x32a9fb67 _ZN29CoreReadStreamCFStreamSupport19coreStreamReadEventEP16__CoreReadStreamm + 99
7. CFNetwork 0x32a9ed57 _ZN20CoreReadStreamClient25coreStreamEventsAvailableEm + 35
8. CFNetwork 0x32aa13d7 _ZN14CoreStreamBase14_callClientNowEv + 47
9. CFNetwork 0x32aa116d _ZN14CoreStreamBase34_streamSetEventAndScheduleDeliveryEmh + 85
10. CFNetwork 0x32aa156b _ZN14CoreStreamBase28_streamInterface_SignalEventEmPK13CFStreamError + 35 
11. CFNetwork 0x32a60fa9 _ZN14HTTPReadStream15selfSignalEventEmPK13CFStreamError + 325
12. CFNetwork 0x32a61931 _ZN14HTTPReadStream11streamEventEm + 157
13. CFNetwork 0x32a9ed57 _ZN20CoreReadStreamClient25coreStreamEventsAvailableEm + 35
14. CFNetwork 0x32aa13d7 _ZN14CoreStreamBase14_callClientNowEv + 47
15. CoreFoundation 0x32d738f7 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
16. CoreFoundation 0x32d7315d **CFRunLoopDoSources0 + 213
17. CoreFoundation 0x32d71f2f __CFRunLoopRun + 647
18. CoreFoundation 0x32ce523d CFRunLoopRunSpecific + 357
19. CoreFoundation 0x32d43c4b CFRunLoopRun + 99
20. MyProject 0x000f3499 +[ASIHTTPRequest runRequests]
21. Foundation 0x336b6231 __NSThread__main** + 973
22. libsystem_c.dylib 0x3b0750e1 _pthread_start + 309

**Comment by jogu** [comment]
You need to narrow down the exact line that's crashing. Also try running with nszombies enabled.

If you're not running the latest version of asihttprequest, upgrade.

It's very likely this is an issue with how ASIHTTPRequest is being called, rather than a bug in ASIHTTPRequest. My suspicion would be that the line will be one that calls the delegate. You need to make sure you call [request setDelegate:nil] before any delegate is dealloced - ASIHTTPRequest does NOT retain it's delegate.

If you do find any evidence of an ASIHTTPRequest bug, please feel free to reopen this and add more detail.
