### ISSUE TITLE
ASINetworkQueue won't run (actually restart)

### ISSUE THREAD

**Issue by wuf810** [pokeb/asi-http-request#38]
Hi, I've got a singleton method that I use to manage downloading.

I'm downloading a lot of files so they are placed in a ASINetworkQueue and run.

All works well until after the user chooses to cancel download (I call a cancelAllOperations on the queue) and the queue is cancelled.

However if the user chooses to start the download again I see the queue fill up with requests, I then call "go" but nothing happens.

The ASINetworkQueue object is retained and still exists (hence the fact I can get a count). It just never runs the second time.

Any ideas?

Thanks, M

**Comment by pokeb** [comment]
Hi

I've just done a quick test, and my cancelled queue seems to restart correctly.

If you can post your code to the google group at http://groups.google.com/group/asihttprequest, I'll take a look.

Best

Ben

**Comment by wuf810** [comment]
Hi Ben,

The issue is definitely related to using a singleton. If I re-initialise the queue before each download, as opposed to just once in the singleton's init method, then everything works.

I would put this down to "my" problem as I don't think it's worth looking into in detail.

So if using a singleton make sure you init the queue each time (especially if having called cancelAllRequests).

Anyway thanks for the response. Apologies also as I just realised I should have used the googlegroups for the discussion.

Regards, Michael.

**Comment by pokeb** [comment]
Hi Michael

It does seem odd. Does it make any difference if you call [queue reset](which in addition to cancelling all the requests will clear the queue delegate and delegate methods, and suspend the queue)?

Perhaps there is something lower down that causes the queue to stop working in some situations, but I'm afraid I don't know if that's likely or not. In most of the example code and tests I create a new queue each time, so that at least should be a reliable fix.

ASINetworkQueue was originally designed for progress tracking, so it probably isn't a perfect fit for a singleton (eg setting delegates on a singleton queue would be a very bad idea). I can appreciate that a singleton queue would be a useful pattern in lots of cases, but if you do stick with a singleton, I'd recommend using a regular NSOperationQueue instead.

Best

Ben

**Comment by wuf810** [comment]
No reset didn't really help. To be honest I'm not convinced that it isn't something I'm doing.

"eg setting delegates on a singleton queue would be a very bad idea"

I'm intrigued by this. I haven't had any issues with using singletons. I'm using all the queue and request delegates without a problem.  Can you explain why it is bad?

Thanks, Michael.

**Comment by pokeb** [comment]
It's fine to set delegates on the requests in the queue, and theoretically, there's no problem with setting a queue delegate on a singleton queue, if you're careful. But almost by definition, a singleton queue will outlive its delegate.

Possibly, your queue delegate never changes, and it might also be an object that is never dealloced, in which case, there's no risk. But I think it's always best to approach delegation in Objective-C with care - requests or queues trying to talk to dellocated delegates is one of the most common problems people encounter with ASIHTTPRequest.
