### ISSUE TITLE
responseString returns nil and responseData returns data

### ISSUE THREAD

**Issue by prime31** [pokeb/asi-http-request#5]
The issue is with the following url and any url after this (replace the 100 with 200, 300, 400, etc):
http://www.craigslist.org/about/best/all/index100.html

The first page of the 'best of' section (http://www.craigslist.org/about/best/all/) works fine.  For all other pages responseString returns nil due to trying to convert the responseData (which is properly downloaded) with the wrong encoding.  ASI tries to use UTF8 when the actual data is ASCII (or at least using NSASCIIStringEncoding will allow the data to be converted to string).

This may or may not be an ASI issue.  I will see if I can get some more info and a fix or if it is just a craigslist.org issue with sending different encoding and actual data.

**Comment by pokeb** [comment]
This is definitely an issue with craigslist. The headers specify the content is in UTF8, while the page content itself is in Latin 1. You can test this yourself by changing the encoding in Safari, all the odd question mark characters are replaced with the characters they are supposed to represent when you set the text encoding to Latin 1. ASIHTTPRequest will default to Latin 1 unless the HTTP headers tell it the otherwise, so the HTTP header is tripping it up.

You can have a mismatch between the HTTP headers and the charset specified in HTML or XML content, I think browsers will always give precedence to the later, though ASIHTTPRequest won't attempt to read charsets from the page content. In this case, craigslist doesn't specify a charset in the HTML anyway.

I expect the issue doesn't show up on the first page because it doesn't contain any non-ascii characters.

You could workaround this issue by setting responseEncoding to NSISOLatin1StringEncoding.

**Comment by prime31** [comment]
As always, you are the man.  Thanks for looking into this.

**Comment by pokeb** [comment]
Cool, will close this.

Best!

**Comment by ghost** [comment]
I have similar problem with empty response string (and even data), while requesting to Plixi service. There are only 5 finished requests in 30 attempts. My code works with Posterous, Facebook, but I can't understand why Plixi requests are failed.
There are no response status code, status string, response string and response data :(.
I received in log : "Incorrect NSStringEncoding value 0x0000 detected. Assuming NSStringEncodingASCII. Will stop this compatiblity mapping behavior in the near future."
