### ISSUE TITLE
How is the downloadcache-branche progressing?

### ISSUE THREAD

**Issue by steipete** [pokeb/asi-http-request#54]
It it already save to use? Want it for a project... Can we merge it into the master?

**Comment by pokeb** [comment]
I think the download cache should be in pretty good shape, feel free to use it in your own stuff (though please do report any issues you find!) I haven't merged it yet because I haven't written any documentation, but this and a couple of the other branches (new-iphone-samples, new-queue-threading-model) should be merged in the next week or so for v1.7.

**Comment by pokeb** [comment]
It's in master now :)

**Comment by steipete** [comment]
Man, you are awesome!
