### ISSUE TITLE
Feature Request: Block Based API

### ISSUE THREAD

**Issue by steipete** [pokeb/asi-http-request#55]
We should introduce a newer, block based API for the finish/fail actions. I'd love to use that instead of those didFinishSelectors. (Works on OS3 too with PLBlocks)

**Comment by pokeb** [comment]
Hi Peter

Jamie added block support for finish and fail in his branch: http://github.com/jamiepinkham/asi-http-request

I will hopefully merge this after the v1.7 release, I have quite a lot on my plate atm! :)

Best

Ben

**Comment by caged** [comment]
I'd just like to put in a vote in favor of block support as well.  It would really help simplify a lot of my code.  It also seems to be the direction Apple is going with their newer APIs (GameCenter is a great example).

**Comment by steipete** [comment]
Hi Ben,

how's your status on the block feature? I'm starting a new app and will use just apply Jamie's patch with your master... i'd love to see it in master though...

**Comment by bobmccune** [comment]
Bump.  I'd love to see Blocks support rolled into the main release.

**Comment by pokeb** [comment]
Ok, here's my first stab at merging Jamie's code with the dev version of ASIHTTPRequest:

http://github.com/pokeb/asi-http-request/tree/blocks-test

I've changed things so that block calls always happen on the main thread, to match delegates. It feels a bit ugly in places at the moment (in my code, not Jamie's), and obviously needs more testing. I'd appreciate any feedback or suggestions.

**Comment by pokeb** [comment]
Ok, blocks support is in master now.
