### ISSUE TITLE
Network Indicator never stops spinning

### ISSUE THREAD

**Issue by marklehmacher** [pokeb/asi-http-request#81]
When using ASIHTTPRequest synchronously (by way of startSynchronous) from within a non-concurrent NSOperation which is executed within an NSOperationQueue the network activity indicator starts spinning but never stops.

The problem is that the selector hideNetworkActivityIndicator as scheduled by performSelector:withObject:afterDelay is never called. My guess is, that NSOperations which are executed in a thread by an NSOperationQueue dont have a running run loop and the scheduled selector thus never gets called.

For myself I worked around the problem by roundtripping to the main thread (which is guaranteed to have a running run loop). That is, I perform a selector on the main thread which then uses performSelector:withObject:afterDelay to schedule hiding the activity indicator on the main thread. The same roundtrip is applied when cancelling the hide timer.

**Comment by pokeb** [comment]
Is there a reason why you aren't just adding the request to a queue and running it asynchronously as normal? ASIHTTPRequests are concurrent NSOperations because it's faster and more memory efficient to use a single thread/runloop for all requests.

Anyway, your fix sounds reasonable. I can see that it might be worth changing things to update the network activity indicator on the main thread when the request is synchronous, since as you point out there's no guarantee a secondary thread will have an active runloop.

**Comment by pyjamasam** [comment]
As an additional note to the reasoning behind using a syncronous request (at least in the way I use it), is that I make a request and then deal with the data and then make another request and process that returned data again.  Each operation has 2 requests involved in sequence.  I also do all this work in my own operation queue.  

I already have a opqueue going because I do other processing with the data returned from the call, and having things all centralized and syncronous makes it easier to follow flow and debug through.

Hopefully that makes sense.  Just through I'd throw in my use case since I ran into this problem as well.

chris.

**Comment by pokeb** [comment]
Ok, I think this should be fixed in the dev branch:

http://github.com/pokeb/asi-http-request/commit/35ea592084145b3332861344f36b52dbcaafa351

**Comment by pokeb** [comment]
This fix is in v1.8, and it seems to be working for me, but please re-open this issue if you're still having problems.

Best,

Ben
